@server=http://localhost:3000
@createdUserId = {{createUser.response.body.$.id}}
 
### Create a User
# @name createUser
POST {{server}}/users
Content-Type: application/json
 
{
    "username": "admin",
    "password": "123"
}
 
### Create a User without name or address
POST {{server}}/users
Content-Type: application/json
 
{
  "username": "antony-teste"
}
 
### Read users
GET {{server}}/users
 
### Read a User by id
GET {{server}}/users/{{createdUserId}}
 
### Read a User by id with invalid id
GET {{server}}/users/x
 
### Update a User
PUT {{server}}/users/{{createdUserId}}
Content-Type: application/json
 
{
  "username": "teste",
  "password": "123"
}
 
### Update a User without name or address
PUT {{server}}/users/{{createdUserId}}
Content-Type: application/json
 
{
  "name": "Cloudflare DNS"
}
 
### Update a User with invalid id
PUT {{server}}/users/x
Content-Type: application/json
 
{
  "username": "usuario-teste",
  "password": "123"
}
 
### Delete a User
DELETE {{server}}/users/{{createdUserId}}
 
### Delete a User with invalid id
DELETE {{server}}/users/x